export const VALIDATE_USER_LOGIN_REQUEST = 'VALIDATE_USER_LOGIN_REQUEST';
export const VALIDATE_USER_LOGIN_SUCCESS = 'VALIDATE_LOGIN_USER_SUCCESS';
export const VALIDATE_USER_LOGIN_FAILURE = 'VALIDATE_USER_LOGIN_FAILURE';
export const VALIDATE_USER_LOGIN_ERROR = 'VALIDATE_USER_LOGIN_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';
export const INVALIDATE_USER_LOGIN_SESSION = 'INVALIDATE_USER_LOGIN_SESSION';

export const FETCH_PUBLICATIONS_DATA_REQUEST = 'FETCH_PUBLICATIONS_DATA_REQUEST';
export const FETCH_PUBLICATIONS_DATA_SUCCESS = 'FETCH_PUBLICATIONS_DATA_SUCCESS';
export const FETCH_PUBLICATIONS_DATA_FAILURE = 'FETCH_PUBLICATIONS_DATA_FAILURE';
